// This file was auto-generated by Fern from our API Definition.

import type * as MktAgiApi from "../../../index.js";

export type PostMessagingConversationsRequest =
    | Record<string, unknown>
    /**
     * Conversation details */
    | MktAgiApi.InternalMessagingInternalWebCreateConversationReq;
