// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         user_id: 1,
 *         id: 1,
 *         target_user_id: 1
 *     }
 */
export interface DeleteGatewayUserIdRoutesIdFiltersTargetUserIdRequest {
    /** User ID */
    user_id: number;
    /** Route ID */
    id: number;
    /** Target user ID */
    target_user_id: number;
}
