// This file was auto-generated by Fern from our API Definition.
import * as MktAgiApi from "./api/index.js";
import { AccountsClient } from "./api/resources/accounts/client/Client.js";
import { AdminClient } from "./api/resources/admin/client/Client.js";
import { AdminBulletinsClient } from "./api/resources/adminBulletins/client/Client.js";
import { AdminMarketplaceClient } from "./api/resources/adminMarketplace/client/Client.js";
import { AdminRevenueClient } from "./api/resources/adminRevenue/client/Client.js";
import { AuthClient } from "./api/resources/auth/client/Client.js";
import { BugReportsClient } from "./api/resources/bugReports/client/Client.js";
import { BulletinsClient } from "./api/resources/bulletins/client/Client.js";
import { ChatClient } from "./api/resources/chat/client/Client.js";
import { CommentsClient } from "./api/resources/comments/client/Client.js";
import { ConversationsClient } from "./api/resources/conversations/client/Client.js";
import { DevicesClient } from "./api/resources/devices/client/Client.js";
import { FilesClient } from "./api/resources/files/client/Client.js";
import { GatewayClient } from "./api/resources/gateway/client/Client.js";
import { IamClient } from "./api/resources/iam/client/Client.js";
import { MarketplaceClient } from "./api/resources/marketplace/client/Client.js";
import { MessagesClient } from "./api/resources/messages/client/Client.js";
import { NotificationsClient } from "./api/resources/notifications/client/Client.js";
import { PaymentsClient } from "./api/resources/payments/client/Client.js";
import { SessionsClient } from "./api/resources/sessions/client/Client.js";
import { UserClient } from "./api/resources/user/client/Client.js";
import { UserGatewayClient } from "./api/resources/userGateway/client/Client.js";
import { UserModelsClient } from "./api/resources/userModels/client/Client.js";
import { UserProvidersClient } from "./api/resources/userProviders/client/Client.js";
import { UserRoutesClient } from "./api/resources/userRoutes/client/Client.js";
import { UserSecretsClient } from "./api/resources/userSecrets/client/Client.js";
import { WalletsClient } from "./api/resources/wallets/client/Client.js";
import { WisdomClient } from "./api/resources/wisdom/client/Client.js";
import { WisdomCommunityClient } from "./api/resources/wisdomCommunity/client/Client.js";
import { WisdomCommunityPublicClient } from "./api/resources/wisdomCommunityPublic/client/Client.js";
import { WisdomMarketplaceClient } from "./api/resources/wisdomMarketplace/client/Client.js";
import { WisdomPublicClient } from "./api/resources/wisdomPublic/client/Client.js";
import { normalizeClientOptionsWithAuth } from "./BaseClient.js";
import { mergeHeaders } from "./core/headers.js";
import * as core from "./core/index.js";
import { mergeAdditionalBodyParameters } from "./core/requestBody.js";
import * as environments from "./environments.js";
import { handleNonStatusCodeError } from "./errors/handleNonStatusCodeError.js";
import * as errors from "./errors/index.js";
export class MktAgiApiClient {
    _options;
    _bugReports;
    _adminBulletins;
    _files;
    _adminMarketplace;
    _adminRevenue;
    _admin;
    _comments;
    _notifications;
    _payments;
    _wallets;
    _auth;
    _bulletins;
    _chat;
    _wisdomCommunityPublic;
    _userGateway;
    _userModels;
    _userProviders;
    _userRoutes;
    _gateway;
    _sessions;
    _iam;
    _marketplace;
    _conversations;
    _messages;
    _devices;
    _wisdomPublic;
    _userSecrets;
    _user;
    _accounts;
    _wisdom;
    _wisdomCommunity;
    _wisdomMarketplace;
    constructor(options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }
    get bugReports() {
        return (this._bugReports ??= new BugReportsClient(this._options));
    }
    get adminBulletins() {
        return (this._adminBulletins ??= new AdminBulletinsClient(this._options));
    }
    get files() {
        return (this._files ??= new FilesClient(this._options));
    }
    get adminMarketplace() {
        return (this._adminMarketplace ??= new AdminMarketplaceClient(this._options));
    }
    get adminRevenue() {
        return (this._adminRevenue ??= new AdminRevenueClient(this._options));
    }
    get admin() {
        return (this._admin ??= new AdminClient(this._options));
    }
    get comments() {
        return (this._comments ??= new CommentsClient(this._options));
    }
    get notifications() {
        return (this._notifications ??= new NotificationsClient(this._options));
    }
    get payments() {
        return (this._payments ??= new PaymentsClient(this._options));
    }
    get wallets() {
        return (this._wallets ??= new WalletsClient(this._options));
    }
    get auth() {
        return (this._auth ??= new AuthClient(this._options));
    }
    get bulletins() {
        return (this._bulletins ??= new BulletinsClient(this._options));
    }
    get chat() {
        return (this._chat ??= new ChatClient(this._options));
    }
    get wisdomCommunityPublic() {
        return (this._wisdomCommunityPublic ??= new WisdomCommunityPublicClient(this._options));
    }
    get userGateway() {
        return (this._userGateway ??= new UserGatewayClient(this._options));
    }
    get userModels() {
        return (this._userModels ??= new UserModelsClient(this._options));
    }
    get userProviders() {
        return (this._userProviders ??= new UserProvidersClient(this._options));
    }
    get userRoutes() {
        return (this._userRoutes ??= new UserRoutesClient(this._options));
    }
    get gateway() {
        return (this._gateway ??= new GatewayClient(this._options));
    }
    get sessions() {
        return (this._sessions ??= new SessionsClient(this._options));
    }
    get iam() {
        return (this._iam ??= new IamClient(this._options));
    }
    get marketplace() {
        return (this._marketplace ??= new MarketplaceClient(this._options));
    }
    get conversations() {
        return (this._conversations ??= new ConversationsClient(this._options));
    }
    get messages() {
        return (this._messages ??= new MessagesClient(this._options));
    }
    get devices() {
        return (this._devices ??= new DevicesClient(this._options));
    }
    get wisdomPublic() {
        return (this._wisdomPublic ??= new WisdomPublicClient(this._options));
    }
    get userSecrets() {
        return (this._userSecrets ??= new UserSecretsClient(this._options));
    }
    get user() {
        return (this._user ??= new UserClient(this._options));
    }
    get accounts() {
        return (this._accounts ??= new AccountsClient(this._options));
    }
    get wisdom() {
        return (this._wisdom ??= new WisdomClient(this._options));
    }
    get wisdomCommunity() {
        return (this._wisdomCommunity ??= new WisdomCommunityClient(this._options));
    }
    get wisdomMarketplace() {
        return (this._wisdomMarketplace ??= new WisdomMarketplaceClient(this._options));
    }
    /**
     * Create the first superadmin user. Only works when no admin exists.
     *
     * @param {MktAgiApi.PostSetupRequest} request
     * @param {MktAgiApiClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MktAgiApi.BadRequestError}
     * @throws {@link MktAgiApi.ConflictError}
     * @throws {@link MktAgiApi.InternalServerError}
     *
     * @example
     *     await client.createInitialSuperadmin({
     *         "key": "value"
     *     })
     */
    createInitialSuperadmin(request, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__createInitialSuperadmin(request, requestOptions));
    }
    async __createInitialSuperadmin(request, requestOptions) {
        const _headers = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join((await core.Supplier.get(this._options.baseUrl)) ??
                (await core.Supplier.get(this._options.environment)) ??
                environments.MktAgiApiEnvironment.Default, "setup"),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body,
                rawResponse: _response.rawResponse,
            };
        }
        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MktAgiApi.BadRequestError(_response.error.body, _response.rawResponse);
                case 409:
                    throw new MktAgiApi.ConflictError(_response.error.body, _response.rawResponse);
                case 500:
                    throw new MktAgiApi.InternalServerError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.MktAgiApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }
        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/setup");
    }
    /**
     * Return whether the system has been initialized with a superadmin user.
     *
     * @param {MktAgiApiClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MktAgiApi.InternalServerError}
     *
     * @example
     *     await client.checkSystemSetupStatus()
     */
    checkSystemSetupStatus(requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__checkSystemSetupStatus(requestOptions));
    }
    async __checkSystemSetupStatus(requestOptions) {
        const _headers = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join((await core.Supplier.get(this._options.baseUrl)) ??
                (await core.Supplier.get(this._options.environment)) ??
                environments.MktAgiApiEnvironment.Default, "setup/status"),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }
        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 500:
                    throw new MktAgiApi.InternalServerError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.MktAgiApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }
        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/setup/status");
    }
    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    async fetch(input, init, requestOptions) {
        return core.makePassthroughRequest(input, init, {
            baseUrl: this._options.baseUrl ?? this._options.environment,
            headers: this._options.headers,
            timeoutInSeconds: this._options.timeoutInSeconds,
            maxRetries: this._options.maxRetries,
            fetch: this._options.fetch,
            logging: this._options.logging,
            getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
        }, requestOptions);
    }
}
