// This file was auto-generated by Fern from our API Definition.

import * as MktAgiApi from "./api/index.js";
import { AccountsClient } from "./api/resources/accounts/client/Client.js";
import { AdminClient } from "./api/resources/admin/client/Client.js";
import { AdminBulletinsClient } from "./api/resources/adminBulletins/client/Client.js";
import { AdminMarketplaceClient } from "./api/resources/adminMarketplace/client/Client.js";
import { AdminRevenueClient } from "./api/resources/adminRevenue/client/Client.js";
import { AuthClient } from "./api/resources/auth/client/Client.js";
import { BugReportsClient } from "./api/resources/bugReports/client/Client.js";
import { BulletinsClient } from "./api/resources/bulletins/client/Client.js";
import { ChatClient } from "./api/resources/chat/client/Client.js";
import { CommentsClient } from "./api/resources/comments/client/Client.js";
import { ConversationsClient } from "./api/resources/conversations/client/Client.js";
import { DevicesClient } from "./api/resources/devices/client/Client.js";
import { FilesClient } from "./api/resources/files/client/Client.js";
import { GatewayClient } from "./api/resources/gateway/client/Client.js";
import { IamClient } from "./api/resources/iam/client/Client.js";
import { MarketplaceClient } from "./api/resources/marketplace/client/Client.js";
import { MessagesClient } from "./api/resources/messages/client/Client.js";
import { NotificationsClient } from "./api/resources/notifications/client/Client.js";
import { PaymentsClient } from "./api/resources/payments/client/Client.js";
import { SessionsClient } from "./api/resources/sessions/client/Client.js";
import { UserClient } from "./api/resources/user/client/Client.js";
import { UserGatewayClient } from "./api/resources/userGateway/client/Client.js";
import { UserModelsClient } from "./api/resources/userModels/client/Client.js";
import { UserProvidersClient } from "./api/resources/userProviders/client/Client.js";
import { UserRoutesClient } from "./api/resources/userRoutes/client/Client.js";
import { UserSecretsClient } from "./api/resources/userSecrets/client/Client.js";
import { WalletsClient } from "./api/resources/wallets/client/Client.js";
import { WisdomClient } from "./api/resources/wisdom/client/Client.js";
import { WisdomCommunityClient } from "./api/resources/wisdomCommunity/client/Client.js";
import { WisdomCommunityPublicClient } from "./api/resources/wisdomCommunityPublic/client/Client.js";
import { WisdomPublicClient } from "./api/resources/wisdomPublic/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";
import { mergeHeaders } from "./core/headers.js";
import * as core from "./core/index.js";
import { mergeAdditionalBodyParameters } from "./core/requestBody.js";
import * as environments from "./environments.js";
import { handleNonStatusCodeError } from "./errors/handleNonStatusCodeError.js";
import * as errors from "./errors/index.js";

export declare namespace MktAgiApiClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class MktAgiApiClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<MktAgiApiClient.Options>;
    protected _bugReports: BugReportsClient | undefined;
    protected _adminBulletins: AdminBulletinsClient | undefined;
    protected _files: FilesClient | undefined;
    protected _adminMarketplace: AdminMarketplaceClient | undefined;
    protected _adminRevenue: AdminRevenueClient | undefined;
    protected _admin: AdminClient | undefined;
    protected _comments: CommentsClient | undefined;
    protected _notifications: NotificationsClient | undefined;
    protected _payments: PaymentsClient | undefined;
    protected _wallets: WalletsClient | undefined;
    protected _auth: AuthClient | undefined;
    protected _bulletins: BulletinsClient | undefined;
    protected _chat: ChatClient | undefined;
    protected _wisdomCommunityPublic: WisdomCommunityPublicClient | undefined;
    protected _userGateway: UserGatewayClient | undefined;
    protected _userModels: UserModelsClient | undefined;
    protected _userProviders: UserProvidersClient | undefined;
    protected _userRoutes: UserRoutesClient | undefined;
    protected _gateway: GatewayClient | undefined;
    protected _sessions: SessionsClient | undefined;
    protected _iam: IamClient | undefined;
    protected _marketplace: MarketplaceClient | undefined;
    protected _conversations: ConversationsClient | undefined;
    protected _messages: MessagesClient | undefined;
    protected _devices: DevicesClient | undefined;
    protected _wisdomPublic: WisdomPublicClient | undefined;
    protected _userSecrets: UserSecretsClient | undefined;
    protected _user: UserClient | undefined;
    protected _accounts: AccountsClient | undefined;
    protected _wisdom: WisdomClient | undefined;
    protected _wisdomCommunity: WisdomCommunityClient | undefined;

    constructor(options: MktAgiApiClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get bugReports(): BugReportsClient {
        return (this._bugReports ??= new BugReportsClient(this._options));
    }

    public get adminBulletins(): AdminBulletinsClient {
        return (this._adminBulletins ??= new AdminBulletinsClient(this._options));
    }

    public get files(): FilesClient {
        return (this._files ??= new FilesClient(this._options));
    }

    public get adminMarketplace(): AdminMarketplaceClient {
        return (this._adminMarketplace ??= new AdminMarketplaceClient(this._options));
    }

    public get adminRevenue(): AdminRevenueClient {
        return (this._adminRevenue ??= new AdminRevenueClient(this._options));
    }

    public get admin(): AdminClient {
        return (this._admin ??= new AdminClient(this._options));
    }

    public get comments(): CommentsClient {
        return (this._comments ??= new CommentsClient(this._options));
    }

    public get notifications(): NotificationsClient {
        return (this._notifications ??= new NotificationsClient(this._options));
    }

    public get payments(): PaymentsClient {
        return (this._payments ??= new PaymentsClient(this._options));
    }

    public get wallets(): WalletsClient {
        return (this._wallets ??= new WalletsClient(this._options));
    }

    public get auth(): AuthClient {
        return (this._auth ??= new AuthClient(this._options));
    }

    public get bulletins(): BulletinsClient {
        return (this._bulletins ??= new BulletinsClient(this._options));
    }

    public get chat(): ChatClient {
        return (this._chat ??= new ChatClient(this._options));
    }

    public get wisdomCommunityPublic(): WisdomCommunityPublicClient {
        return (this._wisdomCommunityPublic ??= new WisdomCommunityPublicClient(this._options));
    }

    public get userGateway(): UserGatewayClient {
        return (this._userGateway ??= new UserGatewayClient(this._options));
    }

    public get userModels(): UserModelsClient {
        return (this._userModels ??= new UserModelsClient(this._options));
    }

    public get userProviders(): UserProvidersClient {
        return (this._userProviders ??= new UserProvidersClient(this._options));
    }

    public get userRoutes(): UserRoutesClient {
        return (this._userRoutes ??= new UserRoutesClient(this._options));
    }

    public get gateway(): GatewayClient {
        return (this._gateway ??= new GatewayClient(this._options));
    }

    public get sessions(): SessionsClient {
        return (this._sessions ??= new SessionsClient(this._options));
    }

    public get iam(): IamClient {
        return (this._iam ??= new IamClient(this._options));
    }

    public get marketplace(): MarketplaceClient {
        return (this._marketplace ??= new MarketplaceClient(this._options));
    }

    public get conversations(): ConversationsClient {
        return (this._conversations ??= new ConversationsClient(this._options));
    }

    public get messages(): MessagesClient {
        return (this._messages ??= new MessagesClient(this._options));
    }

    public get devices(): DevicesClient {
        return (this._devices ??= new DevicesClient(this._options));
    }

    public get wisdomPublic(): WisdomPublicClient {
        return (this._wisdomPublic ??= new WisdomPublicClient(this._options));
    }

    public get userSecrets(): UserSecretsClient {
        return (this._userSecrets ??= new UserSecretsClient(this._options));
    }

    public get user(): UserClient {
        return (this._user ??= new UserClient(this._options));
    }

    public get accounts(): AccountsClient {
        return (this._accounts ??= new AccountsClient(this._options));
    }

    public get wisdom(): WisdomClient {
        return (this._wisdom ??= new WisdomClient(this._options));
    }

    public get wisdomCommunity(): WisdomCommunityClient {
        return (this._wisdomCommunity ??= new WisdomCommunityClient(this._options));
    }

    /**
     * Create the first superadmin user. Only works when no admin exists.
     *
     * @param {MktAgiApi.PostSetupRequest} request
     * @param {MktAgiApiClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MktAgiApi.BadRequestError}
     * @throws {@link MktAgiApi.ConflictError}
     * @throws {@link MktAgiApi.InternalServerError}
     *
     * @example
     *     await client.createInitialSuperadmin({
     *         "key": "value"
     *     })
     */
    public createInitialSuperadmin(
        request: MktAgiApi.PostSetupRequest,
        requestOptions?: MktAgiApiClient.RequestOptions,
    ): core.HttpResponsePromise<MktAgiApi.GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebPasswordAuthResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createInitialSuperadmin(request, requestOptions));
    }

    private async __createInitialSuperadmin(
        request: MktAgiApi.PostSetupRequest,
        requestOptions?: MktAgiApiClient.RequestOptions,
    ): Promise<
        core.WithRawResponse<MktAgiApi.GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebPasswordAuthResponse>
    > {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MktAgiApiEnvironment.Default,
                "setup",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as MktAgiApi.GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebPasswordAuthResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MktAgiApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new MktAgiApi.ConflictError(
                        _response.error.body as MktAgiApi.GithubComMktAgiAixInternalPkgGinxCodeResp,
                        _response.rawResponse,
                    );
                case 500:
                    throw new MktAgiApi.InternalServerError(
                        _response.error.body as MktAgiApi.GithubComMktAgiAixInternalPkgGinxCodeResp,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MktAgiApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/setup");
    }

    /**
     * Return whether the system has been initialized with a superadmin user.
     *
     * @param {MktAgiApiClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MktAgiApi.InternalServerError}
     *
     * @example
     *     await client.checkSystemSetupStatus()
     */
    public checkSystemSetupStatus(requestOptions?: MktAgiApiClient.RequestOptions): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__checkSystemSetupStatus(requestOptions));
    }

    private async __checkSystemSetupStatus(
        requestOptions?: MktAgiApiClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MktAgiApiEnvironment.Default,
                "setup/status",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 500:
                    throw new MktAgiApi.InternalServerError(
                        _response.error.body as MktAgiApi.GithubComMktAgiAixInternalPkgGinxCodeResp,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MktAgiApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/setup/status");
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
                getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
            },
            requestOptions,
        );
    }
}
