// This file was auto-generated by Fern from our API Definition.

import type * as MktAgiApi from "../../../index.js";

export type PostUserMeAvatarUploadUrlRequest =
    | Record<string, unknown>
    /**
     * Upload parameters */
    | MktAgiApi.InternalAccountsInternalWebAvatarUploadUrlReq;
