// This file was auto-generated by Fern from our API Definition.

import type * as MktAgiApi from "../index.js";

export interface AnthropicContentBlock {
    /** tool_result content */
    content?: unknown | undefined;
    id?: string | undefined;
    /** tool_use input (JSON object) */
    input?: number[] | undefined;
    is_error?: boolean | undefined;
    name?: string | undefined;
    /** thinking block signature */
    signature?: string | undefined;
    source?: MktAgiApi.AnthropicImageSource | undefined;
    text?: string | undefined;
    thinking?: string | undefined;
    tool_use_id?: string | undefined;
    type?: string | undefined;
}
