// This file was auto-generated by Fern from our API Definition.

export interface AnthropicInputSchema {
    properties?: Record<string, unknown> | undefined;
    required?: string[] | undefined;
    type?: string | undefined;
}
