// This file was auto-generated by Fern from our API Definition.

export interface GithubComMktAgiAixInternalIamAccessGrant {
    createdAt?: number | undefined;
    createdBy?: number | undefined;
    expiresAt?: number | undefined;
    orderNo?: string | undefined;
    resourceID?: number | undefined;
    resourceType?: string | undefined;
    /** "grant" | "purchase" */
    source?: string | undefined;
    userID?: number | undefined;
}
