// This file was auto-generated by Fern from our API Definition.

/**
 * Preferences is the user's preference object (lang, theme, ...).
 */
export interface GithubComMktAgiAixInternalAccountsInternalDomainUserPreferences {
    /** BCP 47, e.g. "zh-CN" */
    lang?: string | undefined;
    /** "light" | "dark" */
    theme?: string | undefined;
}
