// This file was auto-generated by Fern from our API Definition.

export interface GithubComMktAgiAixInternalPkgGinxResultAny {
    code?: number | undefined;
    data?: unknown | undefined;
    limit?: number | undefined;
    message?: string | undefined;
    page?: number | undefined;
    total?: number | undefined;
    user_message?: string | undefined;
}
