// This file was auto-generated by Fern from our API Definition.

import type * as MktAgiApi from "../index.js";

export interface GithubComCodeKoanLlmSdkGoProtocolAnthropicErrorResponse {
    error?: MktAgiApi.AnthropicErrorDetail | undefined;
    type?: string | undefined;
}
