// This file was auto-generated by Fern from our API Definition.

export interface GithubComCodeKoanLlmSdkGoProtocolAnthropicMessage {
    /** string | []ContentBlock */
    content?: unknown | undefined;
    role?: string | undefined;
}
