// This file was auto-generated by Fern from our API Definition.

import type * as MktAgiApi from "../index.js";

export interface GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamInternalDomainAccessGrant {
    code?: number | undefined;
    data?: MktAgiApi.GithubComMktAgiAixInternalIamInternalDomainAccessGrant[] | undefined;
    limit?: number | undefined;
    message?: string | undefined;
    page?: number | undefined;
    total?: number | undefined;
    user_message?: string | undefined;
}
