// This file was auto-generated by Fern from our API Definition.

export interface GithubComMktAgiAixInternalMessagingInternalDomainConversation {
    created_at?: number | undefined;
    created_by?: number | undefined;
    id?: number | undefined;
    last_message?: string | undefined;
    last_msg_at?: number | undefined;
    max_seq?: number | undefined;
    title?: string | undefined;
    type?: string | undefined;
    uid?: string | undefined;
    updated_at?: number | undefined;
}
