// This file was auto-generated by Fern from our API Definition.

export interface GithubComMktAgiAixInternalPaymentsInternalDomainFeeSellerBreakdown {
    fee?: number | undefined;
    seller_user_id?: number | undefined;
}
