// This file was auto-generated by Fern from our API Definition.

/**
 * User provider with masked API key.
 */
export interface InternalAigatewayInternalWebUserProviderResponse {
    /** APIKey is the masked API key (last 4 characters visible). */
    api_key?: string | undefined;
    /** BaseURL is the API base URL. */
    base_url?: string | undefined;
    /** CreatedAt is the creation timestamp (Unix seconds). */
    created_at?: number | undefined;
    /** Enabled indicates whether the provider is active. */
    enabled?: boolean | undefined;
    /** ID is the provider ID. */
    id?: number | undefined;
    /** Name is the provider display name. */
    name?: string | undefined;
    /** Protocol is the API protocol. */
    protocol?: string | undefined;
    /** UpdatedAt is the last update timestamp (Unix seconds). */
    updated_at?: number | undefined;
    /** UserID is the owner user ID. */
    user_id?: number | undefined;
    /** Visibility is the provider visibility. */
    visibility?: string | undefined;
}
