// This file was auto-generated by Fern from our API Definition.

export interface InternalAigatewayInternalWebAddRouteGrantRequest {
    /** UserID is the target user ID to grant route access. */
    user_id?: number | undefined;
}
