// This file was auto-generated by Fern from our API Definition.

/**
 * 内容节点
 */
export interface InternalWisdomInternalWebWisdomResponse {
    /** 正文 */
    body?: string | undefined;
    /** 变更日志 */
    changelog?: string | undefined;
    /** 所属社区 */
    community_id?: number | undefined;
    /** 置信度 */
    confidence?: number | undefined;
    /** 创建时间 */
    created_at?: number | undefined;
    /** 防御 */
    defencer?: string | undefined;
    /** 描述 */
    description?: string | undefined;
    /** 主键 */
    id?: number | undefined;
    /** 分类 */
    kind?: string | undefined;
    /** 前文 */
    pre_body?: string | undefined;
    /** 承诺 */
    promise?: string | undefined;
    /** 扩展属性 */
    props?: number[] | undefined;
    /** 引用次数 */
    reference_count?: number | undefined;
    /** 反思 */
    reflector?: string | undefined;
    /** 修订号 */
    rev?: number | undefined;
    /** 搜索命中 */
    search_hit_count?: number | undefined;
    /** 标识 */
    slug?: string | undefined;
    /** 标题 */
    title?: string | undefined;
    /** 类型 */
    type?: string | undefined;
    /** 更新时间 */
    updated_at?: number | undefined;
    /** 所属用户 */
    user_id?: number | undefined;
    /** 用户名 */
    username?: string | undefined;
    /** 版本号 */
    version?: number | undefined;
}
