// This file was auto-generated by Fern from our API Definition.

export interface InternalAigatewayInternalWebUsageRecordItem {
    /** CallCount is the number of API calls. */
    call_count?: number | undefined;
    /** CompletionTokens is the total completion tokens generated. */
    completion_tokens?: number | undefined;
    /** ID is the record ID. */
    id?: number | undefined;
    /** ModelID is the model that was used. */
    model_id?: number | undefined;
    /** PromptTokens is the total prompt tokens consumed. */
    prompt_tokens?: number | undefined;
    /** RecordDate is the date of this usage record (YYYY-MM-DD). */
    record_date?: string | undefined;
    /** TotalCost is the total cost (yuan). */
    total_cost?: number | undefined;
    /** TotalTokens is the total tokens consumed. */
    total_tokens?: number | undefined;
}
