// This file was auto-generated by Fern from our API Definition.

export interface InternalBugreportsInternalWebSubmitBugReportRequest {
    context?: number[] | undefined;
    description?: string | undefined;
    label?: string | undefined;
    timestamp?: number | undefined;
    title?: string | undefined;
    url?: string | undefined;
}
