// This file was auto-generated by Fern from our API Definition.

export interface InternalBugreportsInternalWebUpdateBugReportRequest {
    review_notes?: string | undefined;
    status?: string | undefined;
}
