// This file was auto-generated by Fern from our API Definition.

export interface InternalAigatewayInternalWebAddModelGrantRequest {
    /** UserID is the target user ID to grant model access. */
    user_id?: number | undefined;
}
