// This file was auto-generated by Fern from our API Definition.
export var InternalAigatewayInternalWebUpdateUserProviderRequest;
(function (InternalAigatewayInternalWebUpdateUserProviderRequest) {
    /** Protocol is the API protocol (openai or anthropic). */
    InternalAigatewayInternalWebUpdateUserProviderRequest.Protocol = {
        Openai: "openai",
        Anthropic: "anthropic",
    };
})(InternalAigatewayInternalWebUpdateUserProviderRequest || (InternalAigatewayInternalWebUpdateUserProviderRequest = {}));
