// This file was auto-generated by Fern from our API Definition.

/**
 * Transfer to main wallet request body.
 */
export interface InternalPaymentsInternalWebTransferToMainRequest {
    /** IdempotencyKey prevents duplicate transfers. */
    idempotency_key: string;
}
