// This file was auto-generated by Fern from our API Definition.

/**
 * Request to register a push notification device for the current user.
 */
export interface InternalMessagingInternalWebRegisterDeviceReq {
    /** DeviceID is the unique identifier of the device. */
    device_id?: string | undefined;
    /** Platform is the device platform (e.g. "ios", "android", "web"). */
    platform?: string | undefined;
    /** PushToken is the push notification service token for the device. */
    push_token?: string | undefined;
}
