// This file was auto-generated by Fern from our API Definition.

/**
 * User secret metadata including the decrypted value.
 */
export interface InternalAccountsInternalWebUserSecretValueResponse {
    /** CreatedAt is the Unix timestamp of when the secret was created. */
    created_at?: number | undefined;
    /** Description is a human-readable description of the secret. */
    description?: string | undefined;
    /** Key is the unique key identifying this secret within the user's namespace. */
    key?: string | undefined;
    /** UpdatedAt is the Unix timestamp of when the secret was last updated. */
    updated_at?: number | undefined;
    /** UserID is the ID of the user who owns this secret. */
    user_id?: number | undefined;
    /** Value is the decrypted secret value. */
    value?: string | undefined;
}
