// This file was auto-generated by Fern from our API Definition.

export interface InternalFilesInternalWebUpdateFileRequest {
    /** New file name */
    name?: string | undefined;
    /** New visibility (domain.VisibilityPrivate|Public) */
    visibility?: string | undefined;
}
