// This file was auto-generated by Fern from our API Definition.

import type * as MktAgiApi from "../index.js";

export interface InternalCommentsInternalWebCommentTreeVo {
    data?: MktAgiApi.GithubComMktAgiAixInternalCommentsInternalDomainCommentNode[] | undefined;
    next_cursor?: number | undefined;
}
