// This file was auto-generated by Fern from our API Definition.

export interface InternalAigatewayInternalWebTestProviderRequest {
    api_key: string;
    base_url?: string | undefined;
    protocol?: string | undefined;
}
