// This file was auto-generated by Fern from our API Definition.

export interface InternalNotificationsInternalWebSetPreferenceReq {
    channel: string;
    enabled?: boolean | undefined;
    type: string;
}
