// This file was auto-generated by Fern from our API Definition.

export interface InternalAigatewayInternalWebMarketplaceModelItem {
    buyout_price?: number | undefined;
    currency?: string | undefined;
    description?: string | undefined;
    id?: number | undefined;
    input_price?: number | undefined;
    is_purchased?: boolean | undefined;
    listed_at?: number | undefined;
    name?: string | undefined;
    output_price?: number | undefined;
    owner_name?: string | undefined;
    total_calls?: number | undefined;
}
