// This file was auto-generated by Fern from our API Definition.

export interface InternalCommentsInternalWebCreateCommentReq {
    body: string;
    parent_id?: number | undefined;
    target_id: number;
    target_type: string;
}
