// This file was auto-generated by Fern from our API Definition.

export interface InternalWisdomInternalWebPurchaseItemResponse {
    community_id?: number | undefined;
    created_at?: number | undefined;
    order_no?: string | undefined;
    source?: string | undefined;
}
