// This file was auto-generated by Fern from our API Definition.

import type * as MktAgiApi from "../index.js";

export type PostSetupRequest =
    | Record<string, unknown>
    /**
     * Admin credentials */
    | MktAgiApi.InternalAccountsInternalWebSetupRequest;
