// This file was auto-generated by Fern from our API Definition.
import { normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as MktAgiApi from "../../../index.js";
export class WisdomClient {
    _options;
    constructor(options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }
    /**
     * List content nodes with optional filters (kind, type, community_id, etc.)
     *
     * @param {MktAgiApi.GetWisdomRequest} request
     * @param {WisdomClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MktAgiApi.BadRequestError}
     * @throws {@link MktAgiApi.UnauthorizedError}
     * @throws {@link MktAgiApi.InternalServerError}
     *
     * @example
     *     await client.wisdom.listContents()
     */
    listContents(request = {}, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__listContents(request, requestOptions));
    }
    async __listContents(request = {}, requestOptions) {
        const { kind, type: type_, community_id: communityId, min_confidence: minConfidence, promise_search: promiseSearch, offset, limit, } = request;
        const _queryParams = {
            kind,
            type: type_,
            community_id: communityId,
            min_confidence: minConfidence,
            promise_search: promiseSearch,
            offset,
            limit,
        };
        const _authRequest = await this._options.authProvider.getAuthRequest();
        const _headers = mergeHeaders(_authRequest.headers, this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join((await core.Supplier.get(this._options.baseUrl)) ??
                (await core.Supplier.get(this._options.environment)) ??
                environments.MktAgiApiEnvironment.Default, "wisdom"),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }
        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MktAgiApi.BadRequestError(_response.error.body, _response.rawResponse);
                case 401:
                    throw new MktAgiApi.UnauthorizedError(_response.error.body, _response.rawResponse);
                case 500:
                    throw new MktAgiApi.InternalServerError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.MktAgiApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }
        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/wisdom");
    }
    /**
     * Create a new content node in the property graph
     *
     * @param {MktAgiApi.PostWisdomRequest} request
     * @param {WisdomClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MktAgiApi.BadRequestError}
     * @throws {@link MktAgiApi.UnauthorizedError}
     * @throws {@link MktAgiApi.UnprocessableEntityError}
     * @throws {@link MktAgiApi.InternalServerError}
     *
     * @example
     *     await client.wisdom.createContent({
     *         "key": "value"
     *     })
     */
    createContent(request, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__createContent(request, requestOptions));
    }
    async __createContent(request, requestOptions) {
        const _authRequest = await this._options.authProvider.getAuthRequest();
        const _headers = mergeHeaders(_authRequest.headers, this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join((await core.Supplier.get(this._options.baseUrl)) ??
                (await core.Supplier.get(this._options.environment)) ??
                environments.MktAgiApiEnvironment.Default, "wisdom"),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body,
                rawResponse: _response.rawResponse,
            };
        }
        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MktAgiApi.BadRequestError(_response.error.body, _response.rawResponse);
                case 401:
                    throw new MktAgiApi.UnauthorizedError(_response.error.body, _response.rawResponse);
                case 422:
                    throw new MktAgiApi.UnprocessableEntityError(_response.error.body, _response.rawResponse);
                case 500:
                    throw new MktAgiApi.InternalServerError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.MktAgiApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }
        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/wisdom");
    }
    /**
     * Get a content node by ID with optional depth context (0 or 1)
     *
     * @param {MktAgiApi.GetWisdomIdRequest} request
     * @param {WisdomClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MktAgiApi.BadRequestError}
     * @throws {@link MktAgiApi.UnauthorizedError}
     * @throws {@link MktAgiApi.NotFoundError}
     * @throws {@link MktAgiApi.InternalServerError}
     *
     * @example
     *     await client.wisdom.getContent({
     *         id: 1
     *     })
     */
    getContent(request, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__getContent(request, requestOptions));
    }
    async __getContent(request, requestOptions) {
        const { id, depth } = request;
        const _queryParams = {
            depth,
        };
        const _authRequest = await this._options.authProvider.getAuthRequest();
        const _headers = mergeHeaders(_authRequest.headers, this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join((await core.Supplier.get(this._options.baseUrl)) ??
                (await core.Supplier.get(this._options.environment)) ??
                environments.MktAgiApiEnvironment.Default, `wisdom/${core.url.encodePathParam(id)}`),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body,
                rawResponse: _response.rawResponse,
            };
        }
        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MktAgiApi.BadRequestError(_response.error.body, _response.rawResponse);
                case 401:
                    throw new MktAgiApi.UnauthorizedError(_response.error.body, _response.rawResponse);
                case 404:
                    throw new MktAgiApi.NotFoundError(_response.error.body, _response.rawResponse);
                case 500:
                    throw new MktAgiApi.InternalServerError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.MktAgiApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }
        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/wisdom/{id}");
    }
    /**
     * Delete a content node by ID
     *
     * @param {MktAgiApi.DeleteWisdomIdRequest} request
     * @param {WisdomClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MktAgiApi.BadRequestError}
     * @throws {@link MktAgiApi.UnauthorizedError}
     * @throws {@link MktAgiApi.NotFoundError}
     * @throws {@link MktAgiApi.InternalServerError}
     *
     * @example
     *     await client.wisdom.deleteContent({
     *         id: 1
     *     })
     */
    deleteContent(request, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__deleteContent(request, requestOptions));
    }
    async __deleteContent(request, requestOptions) {
        const { id } = request;
        const _authRequest = await this._options.authProvider.getAuthRequest();
        const _headers = mergeHeaders(_authRequest.headers, this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join((await core.Supplier.get(this._options.baseUrl)) ??
                (await core.Supplier.get(this._options.environment)) ??
                environments.MktAgiApiEnvironment.Default, `wisdom/${core.url.encodePathParam(id)}`),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body,
                rawResponse: _response.rawResponse,
            };
        }
        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MktAgiApi.BadRequestError(_response.error.body, _response.rawResponse);
                case 401:
                    throw new MktAgiApi.UnauthorizedError(_response.error.body, _response.rawResponse);
                case 404:
                    throw new MktAgiApi.NotFoundError(_response.error.body, _response.rawResponse);
                case 500:
                    throw new MktAgiApi.InternalServerError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.MktAgiApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }
        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/wisdom/{id}");
    }
    /**
     * Update a content node's fields with optimistic locking via version
     *
     * @param {MktAgiApi.PatchWisdomIdRequest} request
     * @param {WisdomClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MktAgiApi.BadRequestError}
     * @throws {@link MktAgiApi.UnauthorizedError}
     * @throws {@link MktAgiApi.NotFoundError}
     * @throws {@link MktAgiApi.ConflictError}
     * @throws {@link MktAgiApi.UnprocessableEntityError}
     * @throws {@link MktAgiApi.InternalServerError}
     *
     * @example
     *     await client.wisdom.updateContent({
     *         id: 1,
     *         body: {
     *             "key": "value"
     *         }
     *     })
     */
    updateContent(request, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__updateContent(request, requestOptions));
    }
    async __updateContent(request, requestOptions) {
        const { id, body: _body } = request;
        const _authRequest = await this._options.authProvider.getAuthRequest();
        const _headers = mergeHeaders(_authRequest.headers, this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join((await core.Supplier.get(this._options.baseUrl)) ??
                (await core.Supplier.get(this._options.environment)) ??
                environments.MktAgiApiEnvironment.Default, `wisdom/${core.url.encodePathParam(id)}`),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body,
                rawResponse: _response.rawResponse,
            };
        }
        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MktAgiApi.BadRequestError(_response.error.body, _response.rawResponse);
                case 401:
                    throw new MktAgiApi.UnauthorizedError(_response.error.body, _response.rawResponse);
                case 404:
                    throw new MktAgiApi.NotFoundError(_response.error.body, _response.rawResponse);
                case 409:
                    throw new MktAgiApi.ConflictError(_response.error.body, _response.rawResponse);
                case 422:
                    throw new MktAgiApi.UnprocessableEntityError(_response.error.body, _response.rawResponse);
                case 500:
                    throw new MktAgiApi.InternalServerError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.MktAgiApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }
        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PATCH", "/wisdom/{id}");
    }
    /**
     * Get audit log entries for a specific content node
     *
     * @param {MktAgiApi.GetWisdomIdLogsRequest} request
     * @param {WisdomClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MktAgiApi.BadRequestError}
     * @throws {@link MktAgiApi.UnauthorizedError}
     * @throws {@link MktAgiApi.InternalServerError}
     *
     * @example
     *     await client.wisdom.getContentLogs({
     *         id: 1
     *     })
     */
    getContentLogs(request, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__getContentLogs(request, requestOptions));
    }
    async __getContentLogs(request, requestOptions) {
        const { id } = request;
        const _authRequest = await this._options.authProvider.getAuthRequest();
        const _headers = mergeHeaders(_authRequest.headers, this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join((await core.Supplier.get(this._options.baseUrl)) ??
                (await core.Supplier.get(this._options.environment)) ??
                environments.MktAgiApiEnvironment.Default, `wisdom/${core.url.encodePathParam(id)}/logs`),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body,
                rawResponse: _response.rawResponse,
            };
        }
        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MktAgiApi.BadRequestError(_response.error.body, _response.rawResponse);
                case 401:
                    throw new MktAgiApi.UnauthorizedError(_response.error.body, _response.rawResponse);
                case 500:
                    throw new MktAgiApi.InternalServerError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.MktAgiApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }
        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/wisdom/{id}/logs");
    }
    /**
     * Add a directed relation edge from source content to target content
     *
     * @param {MktAgiApi.PostWisdomIdRelationsRequest} request
     * @param {WisdomClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MktAgiApi.BadRequestError}
     * @throws {@link MktAgiApi.UnauthorizedError}
     * @throws {@link MktAgiApi.NotFoundError}
     * @throws {@link MktAgiApi.ConflictError}
     * @throws {@link MktAgiApi.UnprocessableEntityError}
     * @throws {@link MktAgiApi.InternalServerError}
     *
     * @example
     *     await client.wisdom.addRelation({
     *         id: 1,
     *         body: {
     *             "key": "value"
     *         }
     *     })
     */
    addRelation(request, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__addRelation(request, requestOptions));
    }
    async __addRelation(request, requestOptions) {
        const { id, body: _body } = request;
        const _authRequest = await this._options.authProvider.getAuthRequest();
        const _headers = mergeHeaders(_authRequest.headers, this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join((await core.Supplier.get(this._options.baseUrl)) ??
                (await core.Supplier.get(this._options.environment)) ??
                environments.MktAgiApiEnvironment.Default, `wisdom/${core.url.encodePathParam(id)}/relations`),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body,
                rawResponse: _response.rawResponse,
            };
        }
        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MktAgiApi.BadRequestError(_response.error.body, _response.rawResponse);
                case 401:
                    throw new MktAgiApi.UnauthorizedError(_response.error.body, _response.rawResponse);
                case 404:
                    throw new MktAgiApi.NotFoundError(_response.error.body, _response.rawResponse);
                case 409:
                    throw new MktAgiApi.ConflictError(_response.error.body, _response.rawResponse);
                case 422:
                    throw new MktAgiApi.UnprocessableEntityError(_response.error.body, _response.rawResponse);
                case 500:
                    throw new MktAgiApi.InternalServerError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.MktAgiApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }
        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/wisdom/{id}/relations");
    }
    /**
     * Remove a relation edge by relation ID
     *
     * @param {MktAgiApi.DeleteWisdomIdRelationsRidRequest} request
     * @param {WisdomClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MktAgiApi.BadRequestError}
     * @throws {@link MktAgiApi.UnauthorizedError}
     * @throws {@link MktAgiApi.NotFoundError}
     * @throws {@link MktAgiApi.InternalServerError}
     *
     * @example
     *     await client.wisdom.removeRelation({
     *         id: 1,
     *         rid: 1
     *     })
     */
    removeRelation(request, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__removeRelation(request, requestOptions));
    }
    async __removeRelation(request, requestOptions) {
        const { id, rid } = request;
        const _authRequest = await this._options.authProvider.getAuthRequest();
        const _headers = mergeHeaders(_authRequest.headers, this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join((await core.Supplier.get(this._options.baseUrl)) ??
                (await core.Supplier.get(this._options.environment)) ??
                environments.MktAgiApiEnvironment.Default, `wisdom/${core.url.encodePathParam(id)}/relations/${core.url.encodePathParam(rid)}`),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body,
                rawResponse: _response.rawResponse,
            };
        }
        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MktAgiApi.BadRequestError(_response.error.body, _response.rawResponse);
                case 401:
                    throw new MktAgiApi.UnauthorizedError(_response.error.body, _response.rawResponse);
                case 404:
                    throw new MktAgiApi.NotFoundError(_response.error.body, _response.rawResponse);
                case 500:
                    throw new MktAgiApi.InternalServerError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.MktAgiApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }
        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/wisdom/{id}/relations/{rid}");
    }
    /**
     * Trigger community detection clustering on user's content graph
     *
     * @param {WisdomClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MktAgiApi.UnauthorizedError}
     * @throws {@link MktAgiApi.ConflictError}
     * @throws {@link MktAgiApi.InternalServerError}
     *
     * @example
     *     await client.wisdom.clusterContents()
     */
    clusterContents(requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__clusterContents(requestOptions));
    }
    async __clusterContents(requestOptions) {
        const _authRequest = await this._options.authProvider.getAuthRequest();
        const _headers = mergeHeaders(_authRequest.headers, this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join((await core.Supplier.get(this._options.baseUrl)) ??
                (await core.Supplier.get(this._options.environment)) ??
                environments.MktAgiApiEnvironment.Default, "wisdom/cluster"),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body,
                rawResponse: _response.rawResponse,
            };
        }
        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new MktAgiApi.UnauthorizedError(_response.error.body, _response.rawResponse);
                case 409:
                    throw new MktAgiApi.ConflictError(_response.error.body, _response.rawResponse);
                case 500:
                    throw new MktAgiApi.InternalServerError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.MktAgiApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }
        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/wisdom/cluster");
    }
    /**
     * List the current user's purchased community access grants
     *
     * @param {WisdomClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MktAgiApi.UnauthorizedError}
     * @throws {@link MktAgiApi.InternalServerError}
     *
     * @example
     *     await client.wisdom.listPurchasedCommunities()
     */
    listPurchasedCommunities(requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__listPurchasedCommunities(requestOptions));
    }
    async __listPurchasedCommunities(requestOptions) {
        const _authRequest = await this._options.authProvider.getAuthRequest();
        const _headers = mergeHeaders(_authRequest.headers, this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join((await core.Supplier.get(this._options.baseUrl)) ??
                (await core.Supplier.get(this._options.environment)) ??
                environments.MktAgiApiEnvironment.Default, "wisdom/purchases"),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body,
                rawResponse: _response.rawResponse,
            };
        }
        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new MktAgiApi.UnauthorizedError(_response.error.body, _response.rawResponse);
                case 500:
                    throw new MktAgiApi.InternalServerError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.MktAgiApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }
        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/wisdom/purchases");
    }
    /**
     * Get the content subgraph for a specific community
     *
     * @param {MktAgiApi.GetWisdomSubgraphRequest} request
     * @param {WisdomClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MktAgiApi.BadRequestError}
     * @throws {@link MktAgiApi.UnauthorizedError}
     * @throws {@link MktAgiApi.UnprocessableEntityError}
     * @throws {@link MktAgiApi.InternalServerError}
     *
     * @example
     *     await client.wisdom.getSubgraph({
     *         community_id: 1
     *     })
     */
    getSubgraph(request, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__getSubgraph(request, requestOptions));
    }
    async __getSubgraph(request, requestOptions) {
        const { community_id: communityId } = request;
        const _queryParams = {
            community_id: communityId,
        };
        const _authRequest = await this._options.authProvider.getAuthRequest();
        const _headers = mergeHeaders(_authRequest.headers, this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join((await core.Supplier.get(this._options.baseUrl)) ??
                (await core.Supplier.get(this._options.environment)) ??
                environments.MktAgiApiEnvironment.Default, "wisdom/subgraph"),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body,
                rawResponse: _response.rawResponse,
            };
        }
        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MktAgiApi.BadRequestError(_response.error.body, _response.rawResponse);
                case 401:
                    throw new MktAgiApi.UnauthorizedError(_response.error.body, _response.rawResponse);
                case 422:
                    throw new MktAgiApi.UnprocessableEntityError(_response.error.body, _response.rawResponse);
                case 500:
                    throw new MktAgiApi.InternalServerError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.MktAgiApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }
        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/wisdom/subgraph");
    }
}
