// This file was auto-generated by Fern from our API Definition.

import type * as MktAgiApi from "../../../index.js";

export type PutWisdomCommunityIdPricingRequestBody =
    | Record<string, unknown>
    /**
     * Pricing settings */
    | MktAgiApi.InternalWisdomInternalWebSetPricingRequest;
