// This file was auto-generated by Fern from our API Definition.

import type * as MktAgiApi from "../../../index.js";

export type PostGatewayUserIdModelsIdFiltersRequestBody =
    | Record<string, unknown>
    /**
     * Target user ID */
    | MktAgiApi.InternalAigatewayInternalWebAddModelFilterRequest;
