// This file was auto-generated by Fern from our API Definition.

import type * as MktAgiApi from "../../../index.js";

export type PostMessagesRequest =
    | Record<string, unknown>
    /**
     * Anthropic Messages parameters */
    | MktAgiApi.AnthropicMessageRequest;
