// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: 1
 *     }
 */
export interface DeleteIamApiKeysIdRequest {
    /** API key ID */
    id: number;
}
