// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         resource_type: "resource_type",
 *         resource_id: 1
 *     }
 */
export interface GetIamGrantsRequest {
    /** Resource type */
    resource_type: string;
    /** Resource ID */
    resource_id: number;
}
