// This file was auto-generated by Fern from our API Definition.

import type * as MktAgiApi from "../../../index.js";

export type PatchWisdomIdRequestBody =
    | Record<string, unknown>
    /**
     * Update content request */
    | MktAgiApi.InternalWisdomInternalWebUpdateWisdomRequest;
