// This file was auto-generated by Fern from our API Definition.

import type * as MktAgiApi from "../../../index.js";

export type PostWisdomIdRelationsRequestBody =
    | Record<string, unknown>
    /**
     * Add relation request */
    | MktAgiApi.InternalWisdomInternalWebAddRelationRequest;
