// This file was auto-generated by Fern from our API Definition.

import type * as MktAgiApi from "../../../index.js";

export type PostAuthGithubRequest =
    | Record<string, unknown>
    /**
     * GitHub authorization code */
    | MktAgiApi.InternalAccountsInternalWebOauthExchangeReq;
