// This file was auto-generated by Fern from our API Definition.

import type * as MktAgiApi from "../../../index.js";

export type PostAuthEmailSendRequest =
    | Record<string, unknown>
    /**
     * Email address, optional captcha_token and captcha_code */
    | MktAgiApi.InternalAccountsInternalWebEmailSendRequest;
