// This file was auto-generated by Fern from our API Definition.

import type * as MktAgiApi from "../../../index.js";

export type PostAuthEmailVerifyRequest =
    | Record<string, unknown>
    /**
     * Email and verification code */
    | MktAgiApi.InternalAccountsInternalWebEmailVerifyRequest;
