// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as MktAgiApi from "../../../index.js";

export declare namespace AuthClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class AuthClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<AuthClient.Options>;

    constructor(options: AuthClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Generate a CAPTCHA image and return the token plus base64-encoded PNG.
     *
     * @param {AuthClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MktAgiApi.InternalServerError}
     *
     * @example
     *     await client.auth.generateImageCaptcha()
     */
    public generateImageCaptcha(
        requestOptions?: AuthClient.RequestOptions,
    ): core.HttpResponsePromise<MktAgiApi.GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebCaptchaGenerateResponse> {
        return core.HttpResponsePromise.fromPromise(this.__generateImageCaptcha(requestOptions));
    }

    private async __generateImageCaptcha(
        requestOptions?: AuthClient.RequestOptions,
    ): Promise<
        core.WithRawResponse<MktAgiApi.GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebCaptchaGenerateResponse>
    > {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MktAgiApiEnvironment.Default,
                "auth/captcha",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as MktAgiApi.GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebCaptchaGenerateResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 500:
                    throw new MktAgiApi.InternalServerError(
                        _response.error.body as MktAgiApi.GithubComMktAgiAixInternalPkgGinxCodeResp,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MktAgiApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/auth/captcha");
    }

    /**
     * Send a one-time verification code to the given email address. Rate-limited to 1 per 60 seconds.
     *
     * @param {MktAgiApi.PostAuthEmailSendRequest} request
     * @param {AuthClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MktAgiApi.BadRequestError}
     * @throws {@link MktAgiApi.TooManyRequestsError}
     *
     * @example
     *     await client.auth.sendEmailVerificationCode({
     *         "key": "value"
     *     })
     */
    public sendEmailVerificationCode(
        request: MktAgiApi.PostAuthEmailSendRequest,
        requestOptions?: AuthClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__sendEmailVerificationCode(request, requestOptions));
    }

    private async __sendEmailVerificationCode(
        request: MktAgiApi.PostAuthEmailSendRequest,
        requestOptions?: AuthClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MktAgiApiEnvironment.Default,
                "auth/email/send",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MktAgiApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new MktAgiApi.TooManyRequestsError(
                        _response.error.body as MktAgiApi.GithubComMktAgiAixInternalPkgGinxCodeResp,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MktAgiApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/auth/email/send");
    }

    /**
     * Verify the email code and return JWT tokens. Creates a new user account if this email is not registered.
     *
     * @param {MktAgiApi.PostAuthEmailVerifyRequest} request
     * @param {AuthClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MktAgiApi.BadRequestError}
     * @throws {@link MktAgiApi.UnauthorizedError}
     *
     * @example
     *     await client.auth.verifyEmailCodeAndAuthenticate({
     *         "key": "value"
     *     })
     */
    public verifyEmailCodeAndAuthenticate(
        request: MktAgiApi.PostAuthEmailVerifyRequest,
        requestOptions?: AuthClient.RequestOptions,
    ): core.HttpResponsePromise<MktAgiApi.GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebAuthResponse> {
        return core.HttpResponsePromise.fromPromise(this.__verifyEmailCodeAndAuthenticate(request, requestOptions));
    }

    private async __verifyEmailCodeAndAuthenticate(
        request: MktAgiApi.PostAuthEmailVerifyRequest,
        requestOptions?: AuthClient.RequestOptions,
    ): Promise<
        core.WithRawResponse<MktAgiApi.GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebAuthResponse>
    > {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MktAgiApiEnvironment.Default,
                "auth/email/verify",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as MktAgiApi.GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebAuthResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MktAgiApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new MktAgiApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.MktAgiApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/auth/email/verify");
    }

    /**
     * Exchange a GitHub OAuth authorization code for JWT tokens. Use this from SPAs/mobile apps instead of the web redirect flow.
     *
     * @param {MktAgiApi.PostAuthGithubRequest} request
     * @param {AuthClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MktAgiApi.BadRequestError}
     *
     * @example
     *     await client.auth.exchangeGitHubCodeForTokensApi({
     *         "key": "value"
     *     })
     */
    public exchangeGitHubCodeForTokensApi(
        request: MktAgiApi.PostAuthGithubRequest,
        requestOptions?: AuthClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__exchangeGitHubCodeForTokensApi(request, requestOptions));
    }

    private async __exchangeGitHubCodeForTokensApi(
        request: MktAgiApi.PostAuthGithubRequest,
        requestOptions?: AuthClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MktAgiApiEnvironment.Default,
                "auth/github",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MktAgiApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.MktAgiApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/auth/github");
    }

    /**
     * Handle the GitHub OAuth redirect, exchange the code for tokens, and redirect to the frontend.
     *
     * @param {MktAgiApi.GetAuthGithubCallbackRequest} request
     * @param {AuthClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MktAgiApi.BadRequestError}
     *
     * @example
     *     await client.auth.gitHubOAuthCallbackWeb({
     *         state: "state",
     *         code: "code"
     *     })
     */
    public gitHubOAuthCallbackWeb(
        request: MktAgiApi.GetAuthGithubCallbackRequest,
        requestOptions?: AuthClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__gitHubOAuthCallbackWeb(request, requestOptions));
    }

    private async __gitHubOAuthCallbackWeb(
        request: MktAgiApi.GetAuthGithubCallbackRequest,
        requestOptions?: AuthClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { state, code } = request;
        const _queryParams: Record<string, unknown> = {
            state,
            code,
        };
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MktAgiApiEnvironment.Default,
                "auth/github/callback",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MktAgiApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.MktAgiApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/auth/github/callback");
    }

    /**
     * Generate an OAuth state and redirect the browser to GitHub's authorization page.
     *
     * @param {MktAgiApi.GetAuthGithubLoginRequest} request
     * @param {AuthClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MktAgiApi.BadRequestError}
     * @throws {@link MktAgiApi.InternalServerError}
     *
     * @example
     *     await client.auth.initiateGitHubOAuth({
     *         ref_uri: "ref_uri"
     *     })
     */
    public initiateGitHubOAuth(
        request: MktAgiApi.GetAuthGithubLoginRequest,
        requestOptions?: AuthClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__initiateGitHubOAuth(request, requestOptions));
    }

    private async __initiateGitHubOAuth(
        request: MktAgiApi.GetAuthGithubLoginRequest,
        requestOptions?: AuthClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { ref_uri: refUri } = request;
        const _queryParams: Record<string, unknown> = {
            ref_uri: refUri,
        };
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MktAgiApiEnvironment.Default,
                "auth/github/login",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MktAgiApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new MktAgiApi.InternalServerError(
                        _response.error.body as MktAgiApi.GithubComMktAgiAixInternalPkgGinxCodeResp,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MktAgiApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/auth/github/login");
    }

    /**
     * Exchange a Google OAuth authorization code for JWT tokens. Use this from SPAs/mobile apps instead of the web redirect flow.
     *
     * @param {MktAgiApi.PostAuthGoogleRequest} request
     * @param {AuthClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MktAgiApi.BadRequestError}
     *
     * @example
     *     await client.auth.exchangeGoogleCodeForTokensApi({
     *         "key": "value"
     *     })
     */
    public exchangeGoogleCodeForTokensApi(
        request: MktAgiApi.PostAuthGoogleRequest,
        requestOptions?: AuthClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__exchangeGoogleCodeForTokensApi(request, requestOptions));
    }

    private async __exchangeGoogleCodeForTokensApi(
        request: MktAgiApi.PostAuthGoogleRequest,
        requestOptions?: AuthClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MktAgiApiEnvironment.Default,
                "auth/google",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MktAgiApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.MktAgiApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/auth/google");
    }

    /**
     * Handle the Google OAuth redirect, exchange the code for tokens, and redirect to the frontend.
     *
     * @param {MktAgiApi.GetAuthGoogleCallbackRequest} request
     * @param {AuthClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MktAgiApi.BadRequestError}
     *
     * @example
     *     await client.auth.googleOAuthCallbackWeb({
     *         state: "state",
     *         code: "code"
     *     })
     */
    public googleOAuthCallbackWeb(
        request: MktAgiApi.GetAuthGoogleCallbackRequest,
        requestOptions?: AuthClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__googleOAuthCallbackWeb(request, requestOptions));
    }

    private async __googleOAuthCallbackWeb(
        request: MktAgiApi.GetAuthGoogleCallbackRequest,
        requestOptions?: AuthClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { state, code } = request;
        const _queryParams: Record<string, unknown> = {
            state,
            code,
        };
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MktAgiApiEnvironment.Default,
                "auth/google/callback",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MktAgiApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.MktAgiApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/auth/google/callback");
    }

    /**
     * Generate an OAuth state and redirect the browser to Google's authorization page.
     *
     * @param {MktAgiApi.GetAuthGoogleLoginRequest} request
     * @param {AuthClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MktAgiApi.BadRequestError}
     * @throws {@link MktAgiApi.InternalServerError}
     *
     * @example
     *     await client.auth.initiateGoogleOAuth({
     *         ref_uri: "ref_uri"
     *     })
     */
    public initiateGoogleOAuth(
        request: MktAgiApi.GetAuthGoogleLoginRequest,
        requestOptions?: AuthClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__initiateGoogleOAuth(request, requestOptions));
    }

    private async __initiateGoogleOAuth(
        request: MktAgiApi.GetAuthGoogleLoginRequest,
        requestOptions?: AuthClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { ref_uri: refUri } = request;
        const _queryParams: Record<string, unknown> = {
            ref_uri: refUri,
        };
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MktAgiApiEnvironment.Default,
                "auth/google/login",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MktAgiApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new MktAgiApi.InternalServerError(
                        _response.error.body as MktAgiApi.GithubComMktAgiAixInternalPkgGinxCodeResp,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MktAgiApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/auth/google/login");
    }

    /**
     * Invalidate all sessions for the authenticated user.
     *
     * @param {AuthClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MktAgiApi.UnauthorizedError}
     *
     * @example
     *     await client.auth.logoutCurrentUser()
     */
    public logoutCurrentUser(requestOptions?: AuthClient.RequestOptions): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__logoutCurrentUser(requestOptions));
    }

    private async __logoutCurrentUser(requestOptions?: AuthClient.RequestOptions): Promise<core.WithRawResponse<void>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MktAgiApiEnvironment.Default,
                "auth/logout",
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new MktAgiApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.MktAgiApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/auth/logout");
    }

    /**
     * Send a one-time verification code to the given phone number. Rate-limited to 1 per 60 seconds.
     *
     * @param {MktAgiApi.PostAuthSmsSendRequest} request
     * @param {AuthClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MktAgiApi.BadRequestError}
     * @throws {@link MktAgiApi.TooManyRequestsError}
     *
     * @example
     *     await client.auth.sendSmsVerificationCode({
     *         "key": "value"
     *     })
     */
    public sendSmsVerificationCode(
        request: MktAgiApi.PostAuthSmsSendRequest,
        requestOptions?: AuthClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__sendSmsVerificationCode(request, requestOptions));
    }

    private async __sendSmsVerificationCode(
        request: MktAgiApi.PostAuthSmsSendRequest,
        requestOptions?: AuthClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MktAgiApiEnvironment.Default,
                "auth/sms/send",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MktAgiApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new MktAgiApi.TooManyRequestsError(
                        _response.error.body as MktAgiApi.GithubComMktAgiAixInternalPkgGinxCodeResp,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MktAgiApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/auth/sms/send");
    }

    /**
     * Verify the SMS code and return JWT tokens. Creates a new user account if this phone is not registered.
     *
     * @param {MktAgiApi.PostAuthSmsVerifyRequest} request
     * @param {AuthClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MktAgiApi.BadRequestError}
     * @throws {@link MktAgiApi.UnauthorizedError}
     *
     * @example
     *     await client.auth.verifySmsCodeAndAuthenticate({
     *         "key": "value"
     *     })
     */
    public verifySmsCodeAndAuthenticate(
        request: MktAgiApi.PostAuthSmsVerifyRequest,
        requestOptions?: AuthClient.RequestOptions,
    ): core.HttpResponsePromise<MktAgiApi.GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebAuthResponse> {
        return core.HttpResponsePromise.fromPromise(this.__verifySmsCodeAndAuthenticate(request, requestOptions));
    }

    private async __verifySmsCodeAndAuthenticate(
        request: MktAgiApi.PostAuthSmsVerifyRequest,
        requestOptions?: AuthClient.RequestOptions,
    ): Promise<
        core.WithRawResponse<MktAgiApi.GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebAuthResponse>
    > {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MktAgiApiEnvironment.Default,
                "auth/sms/verify",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as MktAgiApi.GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebAuthResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MktAgiApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new MktAgiApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.MktAgiApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/auth/sms/verify");
    }
}
