// This file was auto-generated by Fern from our API Definition.

import type * as MktAgiApi from "../../../index.js";

export type PostMessagingConversationsConvIdMessagesRequestBody =
    | Record<string, unknown>
    /**
     * Message content */
    | MktAgiApi.InternalMessagingInternalWebSendMessageReq;
