// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         community_id: 1
 *     }
 */
export interface GetWisdomSubgraphRequest {
    /** Community ID */
    community_id: number;
}
