// This file was auto-generated by Fern from our API Definition.

import type * as MktAgiApi from "../../../index.js";

export type PostApiV1CommentsRequest =
    | Record<string, unknown>
    /**
     * Comment payload */
    | MktAgiApi.InternalCommentsInternalWebCreateCommentReq;
