// This file was auto-generated by Fern from our API Definition.

import type * as MktAgiApi from "../../../index.js";

export type PutApiV1CommentsIdRequestBody =
    | Record<string, unknown>
    /**
     * Updated body */
    | MktAgiApi.InternalCommentsInternalWebUpdateCommentReq;
