// This file was auto-generated by Fern from our API Definition.

import type * as MktAgiApi from "../../../index.js";

export type PostIamVisibilityFiltersRequest =
    | Record<string, unknown>
    /**
     * Visibility filter request */
    | MktAgiApi.InternalIamInternalWebAddFilterRequest;
