// This file was auto-generated by Fern from our API Definition.

import type * as MktAgiApi from "../../../index.js";

export type PostIamGrantsRequest =
    | Record<string, unknown>
    /**
     * Resource access grant request */
    | MktAgiApi.InternalIamInternalWebGrantAccessRequest;
