// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface GetAdminFilesRequest {
    /** Business context ID */
    biz_id?: string;
    /** Directory path, defaults to / */
    dir_path?: string;
}
