// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         user_id: 1
 *     }
 */
export interface GetGatewayUserIdProvidersRequest {
    /** User ID */
    user_id: number;
}
