// This file was auto-generated by Fern from our API Definition.

import type * as MktAgiApi from "../../../index.js";

export type PatchAdminFilesIdRequestBody =
    | Record<string, unknown>
    /**
     * Update request */
    | MktAgiApi.InternalFilesInternalWebUpdateFileRequest;
