// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as MktAgiApi from "../../../index.js";

export declare namespace WisdomCommunityPublicClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class WisdomCommunityPublicClient {
    protected readonly _options: NormalizedClientOptions<WisdomCommunityPublicClient.Options>;

    constructor(options: WisdomCommunityPublicClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * List public communities without authentication. When slug is provided, username is required for joint lookup.
     *
     * @param {MktAgiApi.GetCommunityRequest} request
     * @param {WisdomCommunityPublicClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MktAgiApi.BadRequestError}
     * @throws {@link MktAgiApi.InternalServerError}
     *
     * @example
     *     await client.wisdomCommunityPublic.listPublicCommunities()
     */
    public listPublicCommunities(
        request: MktAgiApi.GetCommunityRequest = {},
        requestOptions?: WisdomCommunityPublicClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__listPublicCommunities(request, requestOptions));
    }

    private async __listPublicCommunities(
        request: MktAgiApi.GetCommunityRequest = {},
        requestOptions?: WisdomCommunityPublicClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { username, slug, offset, limit } = request;
        const _queryParams: Record<string, unknown> = {
            username,
            slug,
            offset,
            limit,
        };
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MktAgiApiEnvironment.Default,
                "community",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MktAgiApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new MktAgiApi.InternalServerError(
                        _response.error.body as MktAgiApi.GithubComMktAgiAixInternalPkgGinxCodeResp,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MktAgiApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/community");
    }
}
