// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface GetBugReportsMineRequest {
    /** Max results (default 20, max 100) */
    limit?: number;
    /** Page offset */
    offset?: number;
}
