// This file was auto-generated by Fern from our API Definition.

import type * as MktAgiApi from "../../../../index.js";

/**
 * @example
 *     {
 *         key: "key",
 *         body: {
 *             "key": "value"
 *         }
 *     }
 */
export interface PutAdminSysConfigKeyRequest {
    /** 配置键 */
    key: string;
    body: MktAgiApi.PutAdminSysConfigKeyRequestBody;
}
