// This file was auto-generated by Fern from our API Definition.

import type * as MktAgiApi from "../../../index.js";

export type PostGatewaySessionsRequest =
    | Record<string, unknown>
    /**
     * Session details */
    | MktAgiApi.InternalAigatewayInternalWebCreateSessionRequest;
