// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         ref_uri: "ref_uri"
 *     }
 */
export interface GetAuthGithubLoginRequest {
    /** Post-auth redirect URI (will be redirected to verbatim) */
    ref_uri: string;
}
