// This file was auto-generated by Fern from our API Definition.

import type * as MktAgiApi from "../../../../index.js";

/**
 * @example
 *     {
 *         user_id: 1,
 *         id: 1,
 *         body: {
 *             "key": "value"
 *         }
 *     }
 */
export interface PutGatewayUserIdModelsIdRequest {
    /** User ID */
    user_id: number;
    /** Model ID */
    id: number;
    body: MktAgiApi.PutGatewayUserIdModelsIdRequestBody;
}
