// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         conv_id: 1
 *     }
 */
export interface GetMessagingConversationsConvIdRequest {
    /** Conversation ID */
    conv_id: number;
}
